config/routes.rb
Rails.application.routes.draw do
  root 'talks#index'
  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-out', to: 'authentication#destroy'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  resources :talks

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :talks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id].present?
      User.find(session[:user_id])
    end
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome"
      redirect_to root_path
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def new
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Signup Successful"
      redirect_to "/"
    else
      render :new
    end
  end

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
    @talks = Talk.all
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(talk_params)
    if @talk.save
      flash[:notice] = "Talk was successfully added"
      redirect_to talks_path
    else
      render :new
    end
  end

  def show
    @talk = Talk.find(params[:id])
  end

  def edit
    @talk = Talk.find(params[:id])
  end

  def update
    @talk = Talk.find(params[:id])
    if @talk.update(talk_params)
      redirect_to talk_path
    else
      render :edit
    end
  end

  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy
    flash[:notice] = "Talk was successfully deleted"
    redirect_to talks_path
  end

  def talk_params
    params.require(:talk).permit(:speaker, :topic, :date, :time)
  end
  ``
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%=flash[:notice]%>
<%=form_tag sign_in_path do |f|%>
<%=label_tag :email%>
<%=text_field_tag :email %>
<%=label_tag :password %>
<%=password_field_tag :password %>

<%=submit_tag "Sign In"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LightningTalks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%if current_user %>
<%=link_to "Sign out", sign_out_path %>
<%else%>
<%=link_to "Sign in", sign_in_path%>
<%end%>
<%= yield %>

</body>
</html>

app/views/talks/edit.html.erb
<%=form_for @talk do |f|%>
<%=f.label :speaker %>
<%=f.text_field :speaker%>
<%=f.label :topic %>
<%=f.text_field :topic%>
<%=f.label :date %>
<%=f.date_field :date%>
<%=f.label :time %>
<%=f.time_field :time%>
<%=f.submit "Update Talk"%>
<%end%>

app/views/talks/index.html.erb
<%=flash[:notice]%>
<%@talks.each do |talk|%>
  <%=link_to talk.speaker, talk%>
  <%=talk.topic%>
  <%=talk.date%>
  <%=talk.time%>
<%end%>
<%=link_to "New Talk", new_talk_path%>
<%=link_to "Sign In", sign_up_path%>

<%if current_user%>
  <p> Current User is <%=current_user.email%> </p>
  <%else%>
  <p> Nobody is here</p>
<%end%>

app/views/talks/new.html.erb
<%=form_for @talk do |f|%>
<%=f.label :speaker %>
<%=f.text_field :speaker%>
<%=f.label :topic %>
<%=f.text_field :topic%>
<%=f.label :date %>
<%=f.date_field :date%>
<%=f.label :time %>
<%=f.time_field :time%>
<%=f.submit "Add Talk"%>
<%end%>

app/views/talks/show.html.erb
<%=@talk.speaker%>
<%=@talk.topic%>
<%=@talk.date%>
<%=@talk.time%>
<%=link_to "Edit Talk", edit_talk_path%>
<%=link_to "Delete", @talk, method: :delete, data:{confirm: "are you sure you want to erase this record?"}%>